CREATE TRIGGER [aptrx_mstInsert]
ON [aptrx_mst]
INSTEAD OF INSERT
AS
   IF @@ROWCOUNT = 0 RETURN
   
   SET NOCOUNT ON

   DECLARE @SkipBase ListYesNoType
   SET @SkipBase = dbo.SkipBaseTrigger()

   DECLARE @Today DateType
   IF @SkipBase = 0
      SET @Today = dbo.GetCurrentSiteDate()

   DECLARE @UserName LongListType
   IF @SkipBase = 0
      SET @UserName = dbo.UserNameSp()

   INSERT [aptrx_mst] (
      [site_ref]
      , [vend_num]
      , [voucher]
      , [type]
      , [dist_date]
      , [po_num]
      , [inv_num]
      , [inv_date]
      , [inv_amt]
      , [non_disc_amt]
      , [due_days]
      , [due_date]
      , [disc_days]
      , [disc_date]
      , [disc_pct]
      , [disc_amt]
      , [ap_acct]
      , [ref]
      , [post_from_po]
      , [txt]
      , [prox_day]
      , [exch_rate]
      , [includes_tax]
      , [purch_amt]
      , [misc_charges]
      , [sales_tax]
      , [sales_tax_2]
      , [freight]
      , [duty_amt]
      , [brokerage_amt]
      , [tax_code1]
      , [tax_code2]
      , [ap_acct_unit1]
      , [ap_acct_unit2]
      , [ap_acct_unit3]
      , [ap_acct_unit4]
      , [auth_status]
      , [fixed_rate]
      , [prox_code]
      , [grn_num]
      , [NoteExistsFlag]
      , [RecordDate]
      , [RowPointer]
      , [pre_register]
      , [authorizer]
      , [CreatedBy]
      , [UpdatedBy]
      , [CreateDate]
      , [InWorkflow]
      , [insurance_amt]
      , [loc_frt_amt]
      , [include_tax_in_cost]
      , [tax_date]
      , [builder_po_orig_site]
      , [builder_po_num]
      , [builder_voucher_orig_site]
      , [builder_voucher]
      , [auto_vouchered]
      , [cancellation]
      , [fiscal_rpt_system_type]
      , [curr_code]
      , [bg_posting_stat]
      , [PL_vendor_category]
      , [PL_sad_voucher]
      , [PL_manual_vat_voucher]
      , [PL_long_inv_num]
      , [PL_vendor_inv_receipt_date]
      , [PL_multicurrency_invoice]
      , [PL_related_document]
      , [PL_international_bank_account]
      , [FR_item_tax_code1]
      , [FR_item_tax_code2]
      , [ZITbooktype]
      , [ZITcor_per]
      , [ZITenas_amt]
      , [ZITenas_dom]
      , [ZITenas_override]
      , [ZITenas_pct]
      , [ZITenas_period]
      , [ZITenas_year]
      , [ZITLoIDate]
      , [ZITLoINumber]
      , [ZITmonth_pla]
      , [ZITope_coll]
      , [ZITpa_contxml]
      , [ZITpa_ftelet]
      , [ZITpay_hold]
      , [ZITpay_hold_date]
      , [ZITpay_hold_reason]
      , [ZITpay_hold_user]
      , [ZITpr_amt]
      , [ZITpr_tax]
      , [ZITreg_date]
      , [ZITreg_num]
      , [ZITSDI_DataOperaz]
      , [ZITSDI_docTypeRC]
      , [ZITSDI_NaturaRC]
      , [ZITSettlDeadlnReached]
      , [ZITsub_ledger_date]
      , [ZITsub_ledger_nr]
      , [ZITvat_only]
      , [ZITvat_only_amt]
      , [ZITvat_period]
      , [ZITvat_printed]
      , [ZITvat_suf]
      , [ZITvat_year]
      , [ZITVIMNumber]
      , [ZITvouch_seq]
      , [ZITwhh_basis_amt]
      , [ZITwhh_basis_dom]
      , [ZITwhh_comm_nt_amt]
      , [ZITwhh_comm_nt_dom]
      , [ZITwhh_expenses_amt]
      , [ZITwhh_expenses_dom]
      , [ZITwhh_not_taxable_amt]
      , [ZITwhh_not_taxable_dom]
      , [ZITwhh_override]
      , [ZITwhh_pct]
      , [ZITwhh_taxable]
      , [ZITwhh_unconv_amt]
      , [ZITwhh_unconv_dom]
      , [ZITwithhold_amt]
      , [ZITwithhold_dom]
      , [ZITyear_pla]
      , [PL_ksef_indicator]
      , [PL_ksef_id]
      , [VDG_SM_TestNew]
      , [VDG_SM_AnotherCol]
      )
   SELECT
      bt.[site_ref]
      , bt.[vend_num]
      , bt.[voucher]
      , bt.[type]
      , bt.[dist_date]
      , bt.[po_num]
      , bt.[inv_num]
      , bt.[inv_date]
      , bt.[inv_amt]
      , bt.[non_disc_amt]
      , bt.[due_days]
      , bt.[due_date]
      , bt.[disc_days]
      , bt.[disc_date]
      , bt.[disc_pct]
      , bt.[disc_amt]
      , bt.[ap_acct]
      , bt.[ref]
      , bt.[post_from_po]
      , bt.[txt]
      , bt.[prox_day]
      , bt.[exch_rate]
      , bt.[includes_tax]
      , bt.[purch_amt]
      , bt.[misc_charges]
      , bt.[sales_tax]
      , bt.[sales_tax_2]
      , bt.[freight]
      , bt.[duty_amt]
      , bt.[brokerage_amt]
      , bt.[tax_code1]
      , bt.[tax_code2]
      , bt.[ap_acct_unit1]
      , bt.[ap_acct_unit2]
      , bt.[ap_acct_unit3]
      , bt.[ap_acct_unit4]
      , bt.[auth_status]
      , bt.[fixed_rate]
      , bt.[prox_code]
      , bt.[grn_num]
      , bt.[NoteExistsFlag]
      , CASE WHEN @SkipBase = 1 THEN bt.RecordDate ELSE @Today END
      , bt.[RowPointer]
      , bt.[pre_register]
      , bt.[authorizer]
      , CASE WHEN @SkipBase = 1 THEN bt.CreatedBy ELSE @Username END
      , CASE WHEN @SkipBase = 1 THEN bt.UpdatedBy ELSE @Username END
      , CASE WHEN @SkipBase = 1 THEN bt.CreateDate ELSE @Today END
      , bt.[InWorkflow]
      , bt.[insurance_amt]
      , bt.[loc_frt_amt]
      , bt.[include_tax_in_cost]
      , bt.[tax_date]
      , bt.[builder_po_orig_site]
      , bt.[builder_po_num]
      , bt.[builder_voucher_orig_site]
      , bt.[builder_voucher]
      , bt.[auto_vouchered]
      , bt.[cancellation]
      , bt.[fiscal_rpt_system_type]
      , bt.[curr_code]
      , bt.[bg_posting_stat]
      , bt.[PL_vendor_category]
      , bt.[PL_sad_voucher]
      , bt.[PL_manual_vat_voucher]
      , bt.[PL_long_inv_num]
      , bt.[PL_vendor_inv_receipt_date]
      , bt.[PL_multicurrency_invoice]
      , bt.[PL_related_document]
      , bt.[PL_international_bank_account]
      , bt.[FR_item_tax_code1]
      , bt.[FR_item_tax_code2]
      , bt.[ZITbooktype]
      , bt.[ZITcor_per]
      , bt.[ZITenas_amt]
      , bt.[ZITenas_dom]
      , bt.[ZITenas_override]
      , bt.[ZITenas_pct]
      , bt.[ZITenas_period]
      , bt.[ZITenas_year]
      , bt.[ZITLoIDate]
      , bt.[ZITLoINumber]
      , bt.[ZITmonth_pla]
      , bt.[ZITope_coll]
      , bt.[ZITpa_contxml]
      , bt.[ZITpa_ftelet]
      , bt.[ZITpay_hold]
      , bt.[ZITpay_hold_date]
      , bt.[ZITpay_hold_reason]
      , bt.[ZITpay_hold_user]
      , bt.[ZITpr_amt]
      , bt.[ZITpr_tax]
      , bt.[ZITreg_date]
      , bt.[ZITreg_num]
      , bt.[ZITSDI_DataOperaz]
      , bt.[ZITSDI_docTypeRC]
      , bt.[ZITSDI_NaturaRC]
      , bt.[ZITSettlDeadlnReached]
      , bt.[ZITsub_ledger_date]
      , bt.[ZITsub_ledger_nr]
      , bt.[ZITvat_only]
      , bt.[ZITvat_only_amt]
      , bt.[ZITvat_period]
      , bt.[ZITvat_printed]
      , bt.[ZITvat_suf]
      , bt.[ZITvat_year]
      , bt.[ZITVIMNumber]
      , bt.[ZITvouch_seq]
      , bt.[ZITwhh_basis_amt]
      , bt.[ZITwhh_basis_dom]
      , bt.[ZITwhh_comm_nt_amt]
      , bt.[ZITwhh_comm_nt_dom]
      , bt.[ZITwhh_expenses_amt]
      , bt.[ZITwhh_expenses_dom]
      , bt.[ZITwhh_not_taxable_amt]
      , bt.[ZITwhh_not_taxable_dom]
      , bt.[ZITwhh_override]
      , bt.[ZITwhh_pct]
      , bt.[ZITwhh_taxable]
      , bt.[ZITwhh_unconv_amt]
      , bt.[ZITwhh_unconv_dom]
      , bt.[ZITwithhold_amt]
      , bt.[ZITwithhold_dom]
      , bt.[ZITyear_pla]
      , bt.[PL_ksef_indicator]
      , bt.[PL_ksef_id]
      , bt.[VDG_SM_TestNew]
      , bt.[VDG_SM_AnotherCol]
   FROM inserted bt WITH (READUNCOMMITTED)

   -- The AFTER INSERT Triggers fire now, in the following order:
   --   aptrx_mstIup First (if exists; manually maintained)
   --   aptrx_mstInsAudit and/or any custom triggers (if exist; generated by AuditLoggingGenCodeSp and/or manually maintained)
   --   aptrx_mstIupReplicate Last (if exists; generated by ReplicationTriggerIupCode2Sp)

   RETURN