CREATE TRIGGER [aptrxd_mstInsert]
ON [aptrxd_mst]
INSTEAD OF INSERT
AS
   IF @@ROWCOUNT = 0 RETURN
   
   SET NOCOUNT ON

   DECLARE @SkipBase ListYesNoType
   SET @SkipBase = dbo.SkipBaseTrigger()

   DECLARE @Today DateType
   IF @SkipBase = 0
      SET @Today = dbo.GetCurrentSiteDate()

   DECLARE @UserName LongListType
   IF @SkipBase = 0
      SET @UserName = dbo.UserNameSp()

   INSERT [aptrxd_mst] (
      [site_ref]
      , [vend_num]
      , [voucher]
      , [dist_seq]
      , [acct]
      , [amount]
      , [inv_num]
      , [tax_code]
      , [tax_basis]
      , [tax_system]
      , [tax_code_e]
      , [acct_unit1]
      , [acct_unit2]
      , [acct_unit3]
      , [acct_unit4]
      , [proj_num]
      , [task_num]
      , [cost_code]
      , [NoteExistsFlag]
      , [RecordDate]
      , [RowPointer]
      , [CreatedBy]
      , [UpdatedBy]
      , [CreateDate]
      , [InWorkflow]
      , [MX_iso_country_code]
      , [MX_ietu_deduction_pct]
      , [MX_diot_trans_type]
      , [MX_foreign_tax_reg_num]
      , [MX_tax_reg_num]
      , [MX_tax_reg_num_type]
      , [MX_vendor_name]
      , [MX_vat_compliant]
      , [MX_vat_eligible]
      , [ZITco_num]
      , [ZITcost_acct]
      , [ZITdom_amount]
      , [ZITRRDateFrom]
      , [ZITRRDateTo]
      , [ZITsub_ledger_date_dau]
      , [ZITsub_ledger_nr_dau]
      , [ZITvend_num_dau]
      , [ZITvouch_seq]
      )
   SELECT
      bt.[site_ref]
      , bt.[vend_num]
      , bt.[voucher]
      , bt.[dist_seq]
      , bt.[acct]
      , bt.[amount]
      , bt.[inv_num]
      , bt.[tax_code]
      , bt.[tax_basis]
      , bt.[tax_system]
      , bt.[tax_code_e]
      , bt.[acct_unit1]
      , bt.[acct_unit2]
      , bt.[acct_unit3]
      , bt.[acct_unit4]
      , bt.[proj_num]
      , bt.[task_num]
      , bt.[cost_code]
      , bt.[NoteExistsFlag]
      , CASE WHEN @SkipBase = 1 THEN bt.RecordDate ELSE @Today END
      , bt.[RowPointer]
      , CASE WHEN @SkipBase = 1 THEN bt.CreatedBy ELSE @Username END
      , CASE WHEN @SkipBase = 1 THEN bt.UpdatedBy ELSE @Username END
      , CASE WHEN @SkipBase = 1 THEN bt.CreateDate ELSE @Today END
      , bt.[InWorkflow]
      , bt.[MX_iso_country_code]
      , bt.[MX_ietu_deduction_pct]
      , bt.[MX_diot_trans_type]
      , bt.[MX_foreign_tax_reg_num]
      , bt.[MX_tax_reg_num]
      , bt.[MX_tax_reg_num_type]
      , bt.[MX_vendor_name]
      , bt.[MX_vat_compliant]
      , bt.[MX_vat_eligible]
      , bt.[ZITco_num]
      , bt.[ZITcost_acct]
      , bt.[ZITdom_amount]
      , bt.[ZITRRDateFrom]
      , bt.[ZITRRDateTo]
      , bt.[ZITsub_ledger_date_dau]
      , bt.[ZITsub_ledger_nr_dau]
      , bt.[ZITvend_num_dau]
      , bt.[ZITvouch_seq]
   FROM inserted bt WITH (READUNCOMMITTED)

   -- The AFTER INSERT Triggers fire now, in the following order:
   --   aptrxd_mstIup First (if exists; manually maintained)
   --   aptrxd_mstInsAudit and/or any custom triggers (if exist; generated by AuditLoggingGenCodeSp and/or manually maintained)
   --   aptrxd_mstIupReplicate Last (if exists; generated by ReplicationTriggerIupCode2Sp)

   RETURN