CREATE OR ALTER TRIGGER [custaddr_mstInsert]
ON [custaddr_mst]
INSTEAD OF INSERT
AS
   IF @@ROWCOUNT = 0 RETURN
   
   SET NOCOUNT ON

   DECLARE @SkipBase ListYesNoType
   SET @SkipBase = dbo.SkipBaseTrigger()

   DECLARE @Today DateType
   IF @SkipBase = 0
      SET @Today = dbo.GetCurrentSiteDate()

   DECLARE @UserName LongListType
   IF @SkipBase = 0
      SET @UserName = dbo.UserNameSp()

   DECLARE @Severity INT = 0
   DECLARE @Infobar InfobarType
   DECLARE @SavedState LongListType
   
CREATE TABLE #repl (
  from_site NVARCHAR(10) collate database_default
, to_site NVARCHAR(10) collate database_default
, is_trans bit
)
DECLARE @DbName LongListType
SET @DbName = db_name()
INSERT INTO #repl
SELECT DISTINCT source_site, target_site, 0
  FROM rep_rule AS rr
  INNER JOIN rep_object_category AS roc ON
    roc.category = rr.category
  AND roc.object_name = N'custaddr_mst'
  AND roc.object_type = 1 -- Table
  AND roc.to_object_name = roc.object_name
  AND roc.skip_insert = 0
  AND roc.retain_site = 0
INNER JOIN site ON
  site.site = rr.target_site
INNER JOIN site site2 ON
  site2.site = rr.source_site
LEFT OUTER JOIN site_link_info AS sll ON
  sll.from_site = site2.site
AND sll.to_site = rr.target_site
WHERE site2.app_db_name = @DbName
AND site.app_db_name = @DbName
AND rr.source_site IN (SELECT DISTINCT site_ref FROM inserted)
UPDATE #repl SET is_trans = dbo.TransactionalReplication(from_site, to_site, N'custaddr_mst', 1)

   INSERT [custaddr_mst] (
      [site_ref]
      , [cust_num]
      , [cust_seq]
      , [name]
      , [city]
      , [state]
      , [zip]
      , [county]
      , [country]
      , [fax_num]
      , [telex_num]
      , [bal_method]
      , [addr##1]
      , [addr##2]
      , [addr##3]
      , [addr##4]
      , [credit_hold]
      , [credit_hold_user]
      , [credit_hold_date]
      , [credit_hold_reason]
      , [credit_limit]
      , [curr_code]
      , [corp_cust]
      , [corp_cred]
      , [corp_address]
      , [amt_over_inv_amt]
      , [days_over_inv_due_date]
      , [ship_to_email]
      , [bill_to_email]
      , [internet_url]
      , [internal_email_addr]
      , [external_email_addr]
      , [NoteExistsFlag]
      , [RecordDate]
      , [RowPointer]
      , [CreatedBy]
      , [UpdatedBy]
      , [CreateDate]
      , [InWorkflow]
      , [carrier_account]
      , [carrier_upcharge_pct]
      , [carrier_residential_indicator]
      , [carrier_bill_to_transportation]
      , [order_credit_limit]
      , [use_long_name]
      , [long_name]
      , [ZITcust_num_ext]
      , [ZITcust_seq_ext]
      , [ZITdest_loc]
      , [ZITdest_site]
      , [ZITdest_whse]
      , [ZITextend_name1]
      , [ZITextend_name2]
      , [ZITJoinEleB]
      , [ZITPECEmail]
      , [TestingNewColumn]
      )
   SELECT
      bt.[site_ref]
      , bt.[cust_num]
      , bt.[cust_seq]
      , bt.[name]
      , bt.[city]
      , bt.[state]
      , bt.[zip]
      , bt.[county]
      , bt.[country]
      , bt.[fax_num]
      , bt.[telex_num]
      , bt.[bal_method]
      , bt.[addr##1]
      , bt.[addr##2]
      , bt.[addr##3]
      , bt.[addr##4]
      , bt.[credit_hold]
      , bt.[credit_hold_user]
      , bt.[credit_hold_date]
      , bt.[credit_hold_reason]
      , bt.[credit_limit]
      , bt.[curr_code]
      , bt.[corp_cust]
      , bt.[corp_cred]
      , bt.[corp_address]
      , bt.[amt_over_inv_amt]
      , bt.[days_over_inv_due_date]
      , bt.[ship_to_email]
      , bt.[bill_to_email]
      , bt.[internet_url]
      , bt.[internal_email_addr]
      , bt.[external_email_addr]
      , bt.[NoteExistsFlag]
      , CASE WHEN @SkipBase = 1 THEN bt.RecordDate ELSE @Today END
      , bt.[RowPointer]
      , CASE WHEN @SkipBase = 1 THEN bt.CreatedBy ELSE @Username END
      , CASE WHEN @SkipBase = 1 THEN bt.UpdatedBy ELSE @Username END
      , CASE WHEN @SkipBase = 1 THEN bt.CreateDate ELSE @Today END
      , bt.[InWorkflow]
      , bt.[carrier_account]
      , bt.[carrier_upcharge_pct]
      , bt.[carrier_residential_indicator]
      , bt.[carrier_bill_to_transportation]
      , bt.[order_credit_limit]
      , bt.[use_long_name]
      , bt.[long_name]
      , bt.[ZITcust_num_ext]
      , bt.[ZITcust_seq_ext]
      , bt.[ZITdest_loc]
      , bt.[ZITdest_site]
      , bt.[ZITdest_whse]
      , bt.[ZITextend_name1]
      , bt.[ZITextend_name2]
      , bt.[ZITJoinEleB]
      , bt.[ZITPECEmail]
      , bt.[TestingNewColumn]
   FROM inserted bt WITH (READUNCOMMITTED)

   -- The AFTER INSERT Triggers fire now, in the following order:
   --   custaddr_mstIup First (if exists; manually maintained)
   --   custaddr_mstInsAudit and/or any custom triggers (if exist; generated by AuditLoggingGenCodeSp and/or manually maintained)
   --   custaddr_mstIupReplicate Last (if exists; generated by ReplicationTriggerIupCode2Sp)



   EXEC dbo.DefineVariableSp
     @VariableName  = 'ReplInsteadOfInsert'
   , @VariableValue = '1'
   , @Infobar = @Infobar OUTPUT


   -- Skip firing all triggers on replicated row inserts.
   EXEC dbo.SetTriggerStateSp 1, 1, 0, @SavedState OUTPUT, @Infobar OUTPUT


   INSERT [custaddr_mst] (
      [site_ref]
      , [cust_num]
      , [cust_seq]
      , [name]
      , [city]
      , [state]
      , [zip]
      , [county]
      , [country]
      , [fax_num]
      , [telex_num]
      , [bal_method]
      , [addr##1]
      , [addr##2]
      , [addr##3]
      , [addr##4]
      , [credit_hold]
      , [credit_hold_user]
      , [credit_hold_date]
      , [credit_hold_reason]
      , [credit_limit]
      , [curr_code]
      , [corp_cust]
      , [corp_cred]
      , [corp_address]
      , [amt_over_inv_amt]
      , [days_over_inv_due_date]
      , [ship_to_email]
      , [bill_to_email]
      , [internet_url]
      , [internal_email_addr]
      , [external_email_addr]
      , [NoteExistsFlag]
      , [RecordDate]
      , [RowPointer]
      , [CreatedBy]
      , [UpdatedBy]
      , [CreateDate]
      , [InWorkflow]
      , [carrier_account]
      , [carrier_upcharge_pct]
      , [carrier_residential_indicator]
      , [carrier_bill_to_transportation]
      , [order_credit_limit]
      , [use_long_name]
      , [long_name]
      , [ZITcust_num_ext]
      , [ZITcust_seq_ext]
      , [ZITdest_loc]
      , [ZITdest_site]
      , [ZITdest_whse]
      , [ZITextend_name1]
      , [ZITextend_name2]
      , [ZITJoinEleB]
      , [ZITPECEmail]
      , [TestingNewColumn]
      )
   SELECT
      #repl.to_site
      , bt.[cust_num]
      , bt.[cust_seq]
      , bt.[name]
      , bt.[city]
      , bt.[state]
      , bt.[zip]
      , bt.[county]
      , bt.[country]
      , bt.[fax_num]
      , bt.[telex_num]
      , bt.[bal_method]
      , bt.[addr##1]
      , bt.[addr##2]
      , bt.[addr##3]
      , bt.[addr##4]
      , bt.[credit_hold]
      , bt.[credit_hold_user]
      , bt.[credit_hold_date]
      , bt.[credit_hold_reason]
      , bt.[credit_limit]
      , bt.[curr_code]
      , bt.[corp_cust]
      , bt.[corp_cred]
      , bt.[corp_address]
      , bt.[amt_over_inv_amt]
      , bt.[days_over_inv_due_date]
      , bt.[ship_to_email]
      , bt.[bill_to_email]
      , bt.[internet_url]
      , bt.[internal_email_addr]
      , bt.[external_email_addr]
      , bt.[NoteExistsFlag]
      , CASE WHEN @SkipBase = 1 THEN bt.RecordDate ELSE @Today END
      , NEWID()
      , CASE WHEN @SkipBase = 1 THEN bt.CreatedBy ELSE @Username END
      , CASE WHEN @SkipBase = 1 THEN bt.UpdatedBy ELSE @Username END
      , CASE WHEN @SkipBase = 1 THEN bt.CreateDate ELSE @Today END
      , bt.[InWorkflow]
      , bt.[carrier_account]
      , bt.[carrier_upcharge_pct]
      , bt.[carrier_residential_indicator]
      , bt.[carrier_bill_to_transportation]
      , bt.[order_credit_limit]
      , bt.[use_long_name]
      , bt.[long_name]
      , bt.[ZITcust_num_ext]
      , bt.[ZITcust_seq_ext]
      , bt.[ZITdest_loc]
      , bt.[ZITdest_site]
      , bt.[ZITdest_whse]
      , bt.[ZITextend_name1]
      , bt.[ZITextend_name2]
      , bt.[ZITJoinEleB]
      , bt.[ZITPECEmail]
      , bt.[TestingNewColumn]
   FROM #repl, inserted ii
INNER JOIN [custaddr_mst] bt ON
bt.RowPointer = ii.RowPointer
   WHERE  NOT EXISTS (SELECT 1 FROM custaddr_mst rt WHERE rt.site_ref = #repl.to_site AND bt.[cust_num] = rt.[cust_num] AND bt.[cust_seq] = rt.[cust_seq])
   AND bt.site_ref = #repl.from_site
   AND #repl.is_trans = 1
DROP TABLE #repl

   -- Restore trigger state:
   EXEC dbo.RestoreTriggerStateSp 0, @SavedState, @Infobar OUTPUT


   EXEC dbo.UndefineVariableSp
     @VariableName  = 'ReplInsteadOfInsert'
   , @Infobar = @Infobar OUTPUT


   -- The AFTER INSERT Triggers fire now, in the following order:
   --   custaddr_mstIup First (if exists; manually maintained)
   --   custaddr_mstInsAudit and/or any custom triggers (if exist; generated by AuditLoggingGenCodeSp and/or manually maintained)
   --   custaddr_mstIupReplicate Last (if exists; generated by ReplicationTriggerIupCode2Sp)

   RETURN